---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  message = FALSE
)
```

# 计算内循环

## 1. 安装

```{r, eval=FALSE}
devtools::install_github('common2016/MeasureGVC')
```

## 2. 使用

- 内循环计算：`up_inner`为前向链接内循环，`dw_inner`为后向链接内循环。

```{r}
library(MeasureGVC)
library(decompr)
data(leather)
# create intermediate object (class decompr)
decompr_object <- load_tables_vectors(leather)
partici_idx(decompr_object, 'inner')
```

- GVC前向链接参与指数。若前向链接参与指数相对后向链接参与指数更高，意味着该行业更多参与了上游产品制造。

```{r}
partici_idx(decompr_object, 'forward')
```


- GVC后向链接参与指数。

```{r}
partici_idx(decompr_object, 'backward')
```

<!-- ## 3. 参考文献 -->

<!-- - 陈普和傅元海，全球价值链视角下经济内循环测度与应用. 统计研究（已接受）. 2022. -->
<!-- - Wang, Z., Shang-Jin Wei, Xinding Yu, Kunfu Zhu, Measures of Participation in Glabal Value Chains and Global Business Cycles. 2017, NBER. Number:23222. -->
